import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:abayka/services/cart_provider.dart';
import 'package:abayka/services/shop_repository.dart';
import 'package:abayka/services/auth_repository.dart';
import 'package:abayka/order.dart';

class CartScreen extends ConsumerStatefulWidget {
  const CartScreen({super.key});

  @override
  ConsumerState<CartScreen> createState() => _CartScreenState();
}

class _CartScreenState extends ConsumerState<CartScreen> {
  bool _isPlacingOrder = false;

  Future<void> _checkout() async {
    final cartItems = ref.read(cartProvider);
    if (cartItems.isEmpty) return;

    final prefs = await SharedPreferences.getInstance();
    final savedAddress = prefs.getString('user_address') ?? '';
    final addressController = TextEditingController(text: savedAddress);

    final shouldBuy = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Оформление заказа'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              controller: addressController,
              decoration: const InputDecoration(
                labelText: 'Адрес доставки',
                hintText: 'Введите ваш адрес',
                border: OutlineInputBorder(),
              ),
              maxLines: 2,
            ),
            if (savedAddress.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(top: 8.0),
                child: Text(
                  'Использован сохраненный адрес',
                  style: TextStyle(color: Colors.grey[600], fontSize: 12),
                ),
              ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Отмена'),
          ),
          ElevatedButton(
            onPressed: () {
              if (addressController.text.isEmpty) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Введите адрес')),
                );
                return;
              }
              Navigator.pop(context, true);
            },
            child: const Text('Купить'),
          ),
        ],
      ),
    );

    if (shouldBuy != true) return;

    setState(() => _isPlacingOrder = true);

    try {
      final user = ref.read(authRepositoryProvider).currentUser;
      if (user == null) throw Exception('User not logged in');

      final shopRepo = ref.read(shopRepositoryProvider);

      for (final item in cartItems) {
        final order = OrderModel(
          id: '', // Generated by DB
          userId: user.id,
          productId: item.product.id,
          quantity: item.quantity,
          totalPrice: item.totalPrice,
          status: 'pending',
          createdAt: DateTime.now(),
          variantColor: item.color,
          variantSize: item.size,
          address: addressController.text,
        );
        await shopRepo.placeOrder(order);
      }

      ref.read(cartProvider.notifier).clearCart();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Заказ успешно оформлен!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Ошибка оформления заказа: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isPlacingOrder = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final cartItems = ref.watch(cartProvider);
    final totalAmount = cartItems.fold<double>(
        0, (sum, item) => sum + item.totalPrice);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Корзина'),
        actions: [
          if (cartItems.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.delete_sweep),
              onPressed: () => ref.read(cartProvider.notifier).clearCart(),
            ),
        ],
      ),
      body: cartItems.isEmpty
          ? const Center(child: Text('Корзина пуста'))
          : Column(
              children: [
                Expanded(
                  child: ListView.builder(
                    itemCount: cartItems.length,
                    itemBuilder: (context, index) {
                      final item = cartItems[index];
                      return Card(
                        margin: const EdgeInsets.all(8),
                        child: ListTile(
                          leading: item.product.imageUrls.isNotEmpty
                              ? Image.network(item.product.imageUrls.first,
                                  width: 50, height: 50, fit: BoxFit.cover)
                              : const Icon(Icons.image),
                          title: Text(item.product.name),
                          subtitle: Text(
                              '${item.color ?? ''} ${item.size ?? ''} x ${item.quantity}'),
                          trailing: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Text('\$${item.totalPrice.toStringAsFixed(2)}'),
                              IconButton(
                                icon: const Icon(Icons.remove_circle_outline),
                                onPressed: () => ref
                                    .read(cartProvider.notifier)
                                    .removeFromCart(item),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
                ),
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Theme.of(context).cardColor,
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.1),
                        blurRadius: 10,
                        offset: const Offset(0, -5),
                      ),
                    ],
                  ),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Итого:',
                            style: TextStyle(
                                fontSize: 20, fontWeight: FontWeight.bold),
                          ),
                          Text(
                            '\$${totalAmount.toStringAsFixed(2)}',
                            style: const TextStyle(
                                fontSize: 20, fontWeight: FontWeight.bold, color: Colors.green),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton(
                          onPressed: _isPlacingOrder ? null : _checkout,
                          style: ElevatedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                          ),
                          child: _isPlacingOrder
                              ? const CircularProgressIndicator()
                              : const Text('Оформить заказ'),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
    );
  }
}
