import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:abayka/services/products_repository.dart';
import 'package:abayka/product.dart';

class AddProductScreen extends ConsumerStatefulWidget {
  final Product? product;
  const AddProductScreen({super.key, this.product});

  @override
  ConsumerState<AddProductScreen> createState() => _AddProductScreenState();
}

class _AddProductScreenState extends ConsumerState<AddProductScreen> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _nameController;
  late TextEditingController _descriptionController;
  late TextEditingController _typeController;
  late TextEditingController _originalPriceController;
  late TextEditingController _priceController;
  late TextEditingController _discountController;
  
  final List<_VariantController> _variantControllers = [];
  
  List<File> _newImageFiles = [];
  List<String> _existingImageUrls = [];
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    final p = widget.product;
    _nameController = TextEditingController(text: p?.name ?? '');
    _descriptionController = TextEditingController(text: p?.description ?? '');
    _typeController = TextEditingController(text: p?.type ?? '');
    _originalPriceController = TextEditingController(text: p?.originalPrice.toString() ?? '');
    _priceController = TextEditingController(text: p?.price.toString() ?? '');
    _discountController = TextEditingController(text: p?.discount.toString() ?? '');
    
    if (p != null) {
      _existingImageUrls = List.from(p.imageUrls);
      for (var v in p.variants) {
        _variantControllers.add(_VariantController(
          color: v.color,
          size: v.size,
          quantity: v.quantity.toString(),
        ));
      }
    } else {
      _addVariant(); // Add one empty variant by default
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _typeController.dispose();
    _originalPriceController.dispose();
    _priceController.dispose();
    _discountController.dispose();
    for (var c in _variantControllers) {
      c.dispose();
    }
    super.dispose();
  }

  void _addVariant() {
    setState(() {
      _variantControllers.add(_VariantController());
    });
  }

  void _removeVariant(int index) {
    setState(() {
      _variantControllers.removeAt(index);
    });
  }

  Future<void> _pickImages() async {
    final picker = ImagePicker();
    final pickedFiles = await picker.pickMultiImage();
    if (pickedFiles.isNotEmpty) {
      setState(() {
        _newImageFiles.addAll(pickedFiles.map((f) => File(f.path)));
      });
    }
  }

  void _removeNewImage(int index) {
    setState(() {
      _newImageFiles.removeAt(index);
    });
  }

  void _removeExistingImage(int index) {
    setState(() {
      _existingImageUrls.removeAt(index);
    });
  }

  Future<void> _saveProduct() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    try {
      List<String> finalImageUrls = List.from(_existingImageUrls);
      
      if (_newImageFiles.isNotEmpty) {
        final newUrls = await ref.read(productsRepositoryProvider).uploadImages(_newImageFiles);
        finalImageUrls.addAll(newUrls);
      }

      final variants = _variantControllers.map((c) => ProductVariant(
        color: c.colorController.text.trim(),
        size: c.sizeController.text.trim(),
        quantity: int.parse(c.quantityController.text.trim()),
      )).toList();

      final totalQuantity = variants.fold(0, (sum, v) => sum + v.quantity);

      final product = Product(
        id: widget.product?.id ?? '', // ID will be generated by Supabase if empty
        name: _nameController.text.trim(),
        description: _descriptionController.text.trim(),
        type: _typeController.text.trim(),
        quantity: totalQuantity,
        price: double.parse(_priceController.text.trim()),
        originalPrice: double.parse(_originalPriceController.text.trim()),
        discount: double.tryParse(_discountController.text.trim()) ?? 0.0,
        imageUrls: finalImageUrls,
        variants: variants,
      );

      if (widget.product == null) {
        await ref.read(productsRepositoryProvider).addProduct(product);
      } else {
        await ref.read(productsRepositoryProvider).updateProduct(product);
      }
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(widget.product == null ? 'Товар успешно добавлен' : 'Товар обновлен')),
        );
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Ошибка сохранения товара: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.product == null ? 'Добавить товар' : 'Редактировать товар')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: [
                    GestureDetector(
                      onTap: _pickImages,
                      child: Container(
                        width: 100,
                        height: 100,
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: Colors.grey),
                        ),
                        child: const Icon(Icons.add_a_photo, size: 40, color: Colors.grey),
                      ),
                    ),
                    const SizedBox(width: 8),
                    ..._existingImageUrls.asMap().entries.map((entry) {
                      return Stack(
                        children: [
                          Container(
                            width: 100,
                            height: 100,
                            margin: const EdgeInsets.only(right: 8),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(12),
                              image: DecorationImage(
                                image: NetworkImage(entry.value),
                                fit: BoxFit.cover,
                              ),
                            ),
                          ),
                          Positioned(
                            right: 0,
                            top: 0,
                            child: GestureDetector(
                              onTap: () => _removeExistingImage(entry.key),
                              child: const CircleAvatar(
                                radius: 10,
                                backgroundColor: Colors.red,
                                child: Icon(Icons.close, size: 12, color: Colors.white),
                              ),
                            ),
                          ),
                        ],
                      );
                    }),
                    ..._newImageFiles.asMap().entries.map((entry) {
                      return Stack(
                        children: [
                          Container(
                            width: 100,
                            height: 100,
                            margin: const EdgeInsets.only(right: 8),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(12),
                              image: DecorationImage(
                                image: FileImage(entry.value),
                                fit: BoxFit.cover,
                              ),
                            ),
                          ),
                          Positioned(
                            right: 0,
                            top: 0,
                            child: GestureDetector(
                              onTap: () => _removeNewImage(entry.key),
                              child: const CircleAvatar(
                                radius: 10,
                                backgroundColor: Colors.red,
                                child: Icon(Icons.close, size: 12, color: Colors.white),
                              ),
                            ),
                          ),
                        ],
                      );
                    }),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Название'),
                validator: (value) => value == null || value.isEmpty ? 'Введите название' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Описание'),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _typeController,
                decoration: const InputDecoration(labelText: 'Тип (например, Платье, Хиджаб)'),
                validator: (value) => value == null || value.isEmpty ? 'Введите тип' : null,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _originalPriceController,
                      decoration: const InputDecoration(labelText: 'Себестоимость'),
                      keyboardType: TextInputType.number,
                      validator: (value) => value!.isEmpty ? 'Введите цену' : null,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _priceController,
                      decoration: const InputDecoration(labelText: 'Цена продажи'),
                      keyboardType: TextInputType.number,
                      validator: (value) => value!.isEmpty ? 'Введите цену' : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _discountController,
                decoration: const InputDecoration(labelText: 'Скидка (%)'),
                keyboardType: TextInputType.number,
              ),
              const SizedBox(height: 24),
              const Text('Варианты (Цвет, Размер, Кол-во)', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              ..._variantControllers.asMap().entries.map((entry) {
                final index = entry.key;
                final controller = entry.value;
                return Card(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Row(
                      children: [
                        Expanded(
                          child: TextFormField(
                            controller: controller.colorController,
                            decoration: const InputDecoration(labelText: 'Цвет'),
                            validator: (value) => value!.isEmpty ? 'Обязательно' : null,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: TextFormField(
                            controller: controller.sizeController,
                            decoration: const InputDecoration(labelText: 'Размер'),
                            validator: (value) => value!.isEmpty ? 'Обязательно' : null,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: TextFormField(
                            controller: controller.quantityController,
                            decoration: const InputDecoration(labelText: 'Кол-во'),
                            keyboardType: TextInputType.number,
                            validator: (value) => value!.isEmpty ? 'Обязательно' : null,
                          ),
                        ),
                        IconButton(
                          icon: const Icon(Icons.delete, color: Colors.red),
                          onPressed: () => _removeVariant(index),
                        ),
                      ],
                    ),
                  ),
                );
              }),
              TextButton.icon(
                onPressed: _addVariant,
                icon: const Icon(Icons.add),
                label: const Text('Добавить вариант'),
              ),
              const SizedBox(height: 32),
              _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : ElevatedButton(
                      onPressed: _saveProduct,
                      child: Text(widget.product == null ? 'Сохранить товар' : 'Обновить товар'),
                    ),
            ],
          ),
        ),
      ),
    );
  }
}

class _VariantController {
  final TextEditingController colorController;
  final TextEditingController sizeController;
  final TextEditingController quantityController;

  _VariantController({String? color, String? size, String? quantity})
      : colorController = TextEditingController(text: color),
        sizeController = TextEditingController(text: size),
        quantityController = TextEditingController(text: quantity);

  void dispose() {
    colorController.dispose();
    sizeController.dispose();
    quantityController.dispose();
  }
}
